package.path = table.concat({
  "./lua/?.lua",
  "./lua/?/init.lua",
  package.path,
}, ";")

local variants = {
  "techbase",
  "hellbound",
  "escape_velocity",
}

local out_dir = "extra/ls_colors"

local function rgb(hex)
  hex = hex:gsub("#", "")
  return tonumber(hex:sub(1, 2), 16),
    tonumber(hex:sub(3, 4), 16),
    tonumber(hex:sub(5, 6), 16)
end

local function fg(hex)
  local r, g, b = rgb(hex)
  return ("38;2;%d;%d;%d"):format(r, g, b)
end

local function bg(hex)
  local r, g, b = rgb(hex)
  return ("48;2;%d;%d;%d"):format(r, g, b)
end

local function shell_quote(value)
  return "'" .. value:gsub("'", "'\"'\"'") .. "'"
end

local function build_ls_colors(c)
  return table.concat({
    "di=" .. fg(c.important),
    "ln=" .. fg(c.string),
    "ex=" .. fg(c.raw_string),
    "fi=" .. fg(c.normal_fg),
    "or=" .. fg(c.error),
    "mi=" .. fg(c.error),
    "su=" .. fg(c.normal_bg) .. ";" .. bg(c.warn),
    "sg=" .. fg(c.normal_bg) .. ";" .. bg(c.constant),
    "ca=" .. fg(c.normal_bg) .. ";" .. bg(c.error),
    "tw=" .. fg(c.normal_bg) .. ";" .. bg(c.string),
    "ow=" .. fg(c.normal_bg) .. ";" .. bg(c.important),
    "st=" .. fg(c.normal_bg) .. ";" .. bg(c.keyword),
    "*.gitmodules=" .. fg(c.comment_fg),
    "*.gitignore=" .. fg(c.comment_fg),
    "*.lock=" .. fg(c.comment_fg),
    "*.png=" .. fg(c.constant),
    "*.jpg=" .. fg(c.constant),
    "*.jpeg=" .. fg(c.constant),
    "*.gif=" .. fg(c.constant),
    "*.webp=" .. fg(c.constant),
  }, ":")
end

local function write_file(path, body)
  local file = assert(io.open(path, "w"))
  file:write(body)
  file:close()
end

assert(os.execute(('mkdir -p "%s"'):format(out_dir)))

for _, variant in ipairs(variants) do
  local c = require("techbase.palettes." .. variant)
  local ls_colors = build_ls_colors(c)
  local body = table.concat({
    "# Generated by gen_ls_colors.lua; do not edit by hand.",
    "export LS_COLORS=" .. shell_quote(ls_colors),
    "",
  }, "\n")

  write_file(("%s/%s.sh"):format(out_dir, variant), body)
  print(("wrote %s/%s.sh"):format(out_dir, variant))
end
